name: 'Manual Deploy'
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'The command to run'
        default: 'bash /home/ubuntu/deploy-portal.sh'
        required: true

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: ${{ github.event.inputs.command }}
    env:
      GIT_COMMITTER_NAME: GitHub Actions Shell
      GIT_AUTHOR_NAME: GitHub Actions Shell
      EMAIL: github-actions[bot]@users.noreply.github.com
